askmate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('qna/',include('qna_app.urls')),
    path('user/',include('user_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qna_app/urls.py
from django.contrib import admin
from django.urls import path
from .views import addquestion,questions,update_question,delete
from .views import QuestionModelCreateView,QuestionModelListView,question_detail

app_name='qna'

urlpatterns = [
    path('addquestion/',addquestion,name='addquestion'),
    path('read/',questions,name='read'),
    path('delete/<int:id>/',delete,name='delete'),
    path('update/<int:id>/',update_question,name='update'),
    path('create/',QuestionModelCreateView.as_view(),name="create"),
    path('list/',QuestionModelListView.as_view(),name="list"),
    path('detail/<int:id>',question_detail,name="detail")

    # path('test/',test,name='test')

    
    

]

user_app/urls.py
from django.contrib import admin
from django.urls import path
from .views import userauth,logoutauth

app_name = 'user'

urlpatterns = [
    # path('qna/',include('qna_app.urls')),
    path('login/', userauth,name='login'),
    path('logout/', logoutauth,name='logout')
]

qna_app/models.py
from django.db import models

# Create your models here.
#models creates database automatically (ORM(OBJECT RELATION MODEL) CONCEPT)

class CategoryModel(models.Model):
    cat_title = models.CharField(max_length=120)
    cat_desc = models.TextField()
    def __str__(self):
        return(self.cat_title) #shows the title in the website


class QuestionModel(models.Model):
    #id is made by django automatically (built-in)
    title = models.CharField(max_length=255)
    posted_by = models.CharField(max_length=120)
    timestamp = models.DateTimeField(auto_now_add=True)
    question_desc = models.TextField()
    qn_img = models.ImageField(upload_to='QuestionImg', blank= True, null=True)
    qn_votes= models.IntegerField(default=0)
    category = models.ForeignKey(CategoryModel, on_delete=models.CASCADE)

    def __str__(self):
        return(self.question_desc) #shows question description
        


class AnswerModel(models.Model):
    answered_by = models.CharField(max_length=120)
    timestamp = models.DateTimeField(auto_now_add=True)
    answer_desc = models.TextField()
    answer_img = models.ImageField(upload_to='AnswerImg',blank=True, null=True)
    answer_votes = models.IntegerField(default=0)
    is_accept = models.BooleanField(default=0)
    question = models.ForeignKey(QuestionModel, on_delete=models.CASCADE)

    def __str__(self):
        return(self.answer_desc)

user_app/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
 
class UserModel(models.Model):
    name = models.CharField(max_length=120)
    address = models.TextField()
    contact = models.IntegerField()
    email = models.TextField()
    password = models.CharField(max_length=20)
    reputation = models.PositiveIntegerField(validators=[MinValueValidator(0)])

    def __str__(self):
        return (self.name)

qna_app/forms.py
from django import forms
from .models import QuestionModel, AnswerModel,CategoryModel

class QuestionForm(forms.ModelForm):
    class Meta:
        model = QuestionModel
        fields = '__all__'
        

qna_app/views.py
from django.shortcuts import render,redirect
from .models import QuestionModel,CategoryModel
from django.http import HttpResponse
from django.views.generic import CreateView,ListView
from .forms import QuestionForm, AnswerModel#import form from forms.py
 
# Create your views here.

class QuestionModelCreateView(CreateView):
    model=QuestionModel
    fields = '__all__'

class QuestionModelListView(ListView):
    model=QuestionModel
    queryset = QuestionModel.objects.all()

def addquestion(request):

    if request.method == 'POST':
        form=QuestionForm(request.POST,request.FILES)
        if form.is_valid():
            try:
                print(form)
                form.save() #saves data in database 
                return HttpResponse("your form is submitted")
            except:
                return HttpResponse("no data was stored")
        else:
            # print('error')
            # print(form, '00000000000000000000')
            return HttpResponse(form.errors)


    else:
        # form=QuestionForm
        category=CategoryModel.objects.all()
        return render(request,'questionmodel_create.html',{'category':category})


def update_question(request,id):
    question=QuestionModel.objects.get(id=id)
    if request.method == 'POST':
        form=QuestionForm(request.POST,request.FILES)
        if form.is_valid():
            try:
                form.save() #saves data in database 
                return redirect('qna:read')
            except:
                return HttpResponse("failure")
        else:
            return HttpResponse(form.errors)
    else:
        form=QuestionForm(instance=question)
        return render(request,'questionmodel_update.html',{'form':form})


def delete(request,id):
    question = QuestionModel.objects.get(id=id)
    question.delete()
    return redirect('qna:read')

def questions(request):
    if('id' in request.session):
        quest = QuestionModel.objects.all()
        return render(request,'questionmodel_list.html',{'questions':quest})
    else:
        return redirect('user:login')

def question_detail(request,id):
    question= QuestionModel.objects.get(id=id)
    #answer = AnswerModel.objects.get(id=id)

    dic={
        'question' : question,
        #'answer' : answer
    }
    return render(request,'details.html',dic)
    

user_app/views.py
from django.shortcuts import render,redirect
from .models import UserModel
from django.http import HttpResponse
# Create your views here.

def userauth(request):
    if request.method == 'POST':
        e=request.POST.get('email')
        p = request.POST.get('pass')
        user = UserModel.objects.filter(email=e,password=p)
        if(user.count()>0):
            for user in user:
                request.session['email']=user.email #invokes session
                request.session['id']=user.id
                request.session['name']=user.name
                return redirect('qna:read')
        else:
            return HttpResponse("wrong credentials")
    else:
        return render(request, 'login.html')


def logoutauth(request):
    request.session.flush()
    return redirect('user:login')

def test(request):
    return render(request, 'test.html')

qna_app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>
        
        {%block title%}
            ASKMATE
        {% endblock %}
    </title>
  </head>
  <body>
    
    {% block main_body %}
        hello world
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

qna_app/templates/details.html
{% extends 'base.html'%}
{% block title%}
   {{question.title}}
{% endblock %}
{%block main_body%}
{%for answer in answer%}
<div class="card">
    <div class="card-body">
        <h5>{{question.title}}</h5>
        Votes:{{qn.votes}}
        Asked by:amisha
    </div>
</div>
{% endfor %}
{%endblock%}

qna_app/templates/newquestion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    this is new question
    {% for q in question %}
        <h1> {{q.title}} </h1>
        <h2>{{q.question_desc}}</h2>
        <h3> {{ q.timestamp}}</h3>
        <h4> {{q.qn_img}}</h4>
        <img src="../../media/{{q.qn_img}}" alt="img">
    {% endfor %}
</body>
</html>

qna_app/templates/qna_app/questionmodel_form.html
{{object_create}}

qna_app/templates/qna_app/questionmodel_list.html
{{object_list}}

qna_app/templates/questionmodel_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    this is new question
    {% for q in questions %}
        <h1> {{q.title}} </h1>
        <h2>{{q.question_desc}}</h2>
        <h3> {{ q.timestamp}}</h3>
        <h4> {{q.qn_img}}</h4>
        <img src="../../media/{{q.qn_img}}" alt="img" />

        <a href="{%url 'qna:update' q.id %}" ><button> update</button> </a>
        <a href="{% url 'qna:delete' q.id %}" > <button> delete </button></a>

    {% endfor %}
    
    <a href="{% url 'qna:addquestion' %}" > <button> ADD </button></a>
</body>
</html>

qna_app/templates/questionmodel_list.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <link href="{% static 'css/main.css' %}" rel='stylesheet'/>
    <title>Document</title>
</head>
<body>
    <a href="{% url 'user:logout'%}"> <button>LOGOUT</button> </a>
        {% for q in questions %}
        <a href = "{% url 'qna:detail' q.id %}">

        <h1>  {{q.title}} </h1>
        </a>

        <h2>{{q.question_desc}}</h2>
        <h3> {{ q.timestamp}}</h3>
        <h4> {{q.qn_img}}</h4>
        <img src="../../media/{{q.qn_img}}" alt="img" />

        <a href="{%url 'qna:update' q.id %}" ><button> update</button> </a>
        <a href="{% url 'qna:delete' q.id %}" > <button> delete </button></a>

    {% endfor %}
    
    <a href="{% url 'qna:addquestion' %}" > <button> ADD </button></a>
</body>
</html>

qna_app/templates/questionmodel_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form method="POST", enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
            <input type="submit" value="update"/>
        
    </form>
</body>
</html>

qna_app/templates/test.html
{%extends 'base.html'%}

{%blo}

user_app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
        <form action="" method="POST">
            {% csrf_token %}
        <div class="login text-center">
        <h1>Login to your account</h1></div><br>
      Username:<br>
      <input type="text" class="form-control" name="email">
      <br>
      Password:<br>
      <input type="password" class="form-control" name="pass">
      <!-- <small><a href="#">Forgot password</a></small> -->
      <br><br>
        <button type="submit" name="login" class="btn btn-success">Login</button>
    </form>
</body>
</html>